spring:
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9003/trainingdb
    username: SA
    password: ''
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect

